dynamodb:
  local:
    params:
      region: localhost
      endpoint: http://127.0.0.1:8007
    table: pets-local-application
  remote:
    params: {}
    table: pets-application-details

functions:
  - getPetsApplication:
      method: GET
      path: /application-details
      proxy: null
      function: getPetsApplication

serverless:
  basePath: /${BRANCH}
  port: 3005
