services:
  localstack:
    image: localstack/localstack:4.3.0
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - DYNAMODB_IN_MEMORY=1
      - LAMBDA_DOCKER_FLAGS=-e LOCALSTACK_FILE_WATCHER_STRATEGY=polling
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 20

    volumes:
      - "./.localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
