dynamodb:
 local:
   params:
     region: localhost
     endpoint: http://127.0.0.1:8007
   table: pets-local-clinics
 local-global:
   params:
     region: localhost
     endpoint: http://127.0.0.1:8007
   table: pets-local-global-clinics
 remote:
   params: {}
   table: pets-dev-clinics-001

functions:
  - getPetsClinics:
      method: GET
      path: /clinics
      proxy: null
      function: getPetsClinics
  - getPetsClinic:
      method: GET
      path: /clinics/{+proxy}
      proxy: :petsClinicId
      function: getPetsClinic

serverless:
  basePath: /${BRANCH}
  port: 3004
