name: Pets UI Deployment - Test

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [release/*]
    paths:
      - "app/**"

jobs:
  pets-ui:
    uses: ./.github/workflows/app-deploy.yaml
    with:
      environment: "test"
    secrets: inherit
