name: Pets UI Deployment - Dev

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [main]
    paths: "app/**"
  push:
    branches: [feature/TBBETA-476]

jobs:
  uses: ./.github/workflows/app-deploy.yaml
  with:
    environment: "dev"
