name: Pets UI Deployment - Test

on:
  workflow_dispatch:
  # pull_request:
  #   types: [closed]
  #   branches: [main]
  #   paths:
  #     - "pets-ui/**"

jobs:
  pets-ui:
    uses: ./.github/workflows/app-deploy.yaml
    with:
      environment: "preprod"
    secrets: inherit
