name: Pets UI Deployment - Dev

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [main]
    paths: "app/**"

jobs:
  pets-ui:
    uses: ./.github/workflows/templates/app-deploy.yaml
    with:
      environment: "dev"
    secrets: inherit
