name: Pets Clinic Service Deployment

on:
  merge:
    branches: [main]
    paths: "core-services/clinic-service/**"
  workflow_dispatch:

jobs:
  upload:
    name: Upload handler
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "yarn"
      - name: Upload handler file
        uses: actions/upload-artifact@v4
        with:
          name: handler
          path: core-services/clinic-service/handler.js
          if-no-files-found: error

  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    needs: [upload]

    steps:
      - name: Download build file
        uses: actions/download-artifact@v4
        with:
          name: handler
          path: deploy/
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "eu-west-2"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_PETS_CLINIC_SERVICE_ROLE_NAME }}"
          role-session-name: PETS-Clinic-Service-Deploy
      - name: Upload App to S3
        working-directory: deploy/
        run: aws s3 sync . s3://${{ secrets.AWS_PETS_CLINIC_SERVICE_S3_BUCKET_NAME }} --sse aws:kms --sse-kms-key-id ${{ secrets.AWS_PETS_UI_S3_SSE_KEY }}
