name: Pets Clinic Service Deployment - Test

on:
  workflow_dispatch:

jobs:
  clinic-service:
    uses: ./.github/workflows/templates/clinic-service-deploy.yaml
    with:
      environment: "test"
    secrets: inherit
