name: Pets Clinic Service Deployment - Test

on:
  workflow_dispatch:
  push:
    branches: [feature/TBBETA-466]

jobs:
  clinic-service:
    uses: ./.github/workflows/clinic-service-deploy.yaml
    with:
      environment: "test"
    secrets: inherit
