name: Pets Core Services Deployment - Test

on:
  workflow_dispatch:

jobs:
  clinic-service:
    uses: ./.github/workflows/core-services-deploy.yaml
    with:
      environment: "test"
    secrets: inherit
