name: Pets Core Services Deployment - Dev

on:
  workflow_dispatch:

jobs:
  clinic-service:
    uses: ./.github/workflows/core-services-deploy.yaml
    with:
      environment: "dev"
    secrets: inherit
