name: Pets Core Services Deployment - Test

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [release/*]
    paths:
      - "core-services/applicant-service/**"
      - "core-services/clinic-service/**"
      - "core-services/lambda-authoriser/**"

jobs:
  deploy:
    uses: ./.github/workflows/core-services-deploy.yaml
    with:
      environment: "test"
    secrets: inherit
