name: Pets Core Services Deployment - Dev

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - "core-services/clinic-service/**"
      - "core-services/lambda-authoriser/**"
  push:
    branches: [feature/TBBETA-490]

jobs:
  clinic-service:
    uses: ./.github/workflows/core-services-deploy.yaml
    with:
      environment: "dev"
    secrets: inherit
