name: Pets Deployment - Test

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [release/*]
    paths:
      - "core-services/applicant-service/**"
      - "core-services/clinic-service/**"
      - "core-services/lambda-authoriser/**"
      - "pets-ui/**"

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: "qat"
    secrets: inherit
